import type { Payload, PayloadRequest } from "payload";

/**
 * Generated seed file for sdsd
 * Auto-generated by Velen Website Builder
 */
export const seed = async ({
  payload,
  req,
}: {
  payload: Payload;
  req: PayloadRequest;
}): Promise<void> => {
  payload.logger.info("Seeding sdsd...");

  try {
    // Create home page
    const homePage = await payload.create({
      collection: 'pages',
      data: {
        title: "sdsd",
        slug: "/",
        layout: [
    {
      blockType: "featureCard",
      id: "block-0",
      heading: "Feature Title",
      description: "Feature description goes here",
      variant: "default"
    },
    {
      blockType: "cardsCarousel",
      id: "block-1",
      title: "carousel",
      cards: [{"title":"test","subtitle":"test","image":{"id":15,"alt":"ClearPath-Logo-Final-Nov-6_Bird-w-swoosh-blue.svg","caption":null,"_key":null,"updatedAt":"2025-12-15T20:25:00.325Z","createdAt":"2025-12-15T20:25:00.325Z","url":"/api/media/file/ClearPath-Logo-Final-Nov-6_Bird-w-swoosh-blue.svg","thumbnailURL":null,"filename":"ClearPath-Logo-Final-Nov-6_Bird-w-swoosh-blue.svg","mimeType":"image/svg+xml","filesize":1433,"width":189,"height":172,"focalX":null,"focalY":null,"sizes":{"thumbnail":{"_key":null,"url":null,"width":null,"height":null,"mimeType":null,"filesize":null,"filename":null},"square":{"_key":null,"url":null,"width":null,"height":null,"mimeType":null,"filesize":null,"filename":null},"small":{"_key":null,"url":null,"width":null,"height":null,"mimeType":null,"filesize":null,"filename":null},"medium":{"_key":null,"url":null,"width":null,"height":null,"mimeType":null,"filesize":null,"filename":null},"large":{"_key":null,"url":null,"width":null,"height":null,"mimeType":null,"filesize":null,"filename":null},"xlarge":{"_key":null,"url":null,"width":null,"height":null,"mimeType":null,"filesize":null,"filename":null},"og":{"_key":null,"url":null,"width":null,"height":null,"mimeType":null,"filesize":null,"filename":null}}}},{"title":"scscs","subtitle":"cscscss","image":null},{"title":"scscs","subtitle":"cscscs","image":null},{"title":"scscs","subtitle":"cscscscaa","image":null}]
    }
        ],
        _status: 'published',
      },
    });

    payload.logger.info(`✓ Created home page: ${homePage.id}`);

    // Update header global
    await payload.updateGlobal({
      slug: 'header',
      data: {
        navItems: [
        ],
      },
    });

    payload.logger.info("✓ Updated header navigation");

    // Update footer global
    await payload.updateGlobal({
      slug: 'footer',
      data: {
        navItems: [
          {
            link: {
              type: 'custom',
              label: 'Home',
              url: '/',
            }
          }
        ],
      },
    });

    payload.logger.info("✓ Updated footer");

    payload.logger.info("Seeded sdsd successfully! 🎉");
  } catch (error) {
    payload.logger.error("Seeding failed:", error);
    throw error;
  }
};
